spring:
  application:
    name: notification-service
  config:
    import: "configserver:http://${SPRING_SECURITY_USER}:${SPRING_SECURITY_PASSWORD}@config-service:8001"
  cloud:
    config:
      fail-fast: true