spring:
  application:
    name: notification-service
  config:
    import: "configserver:http://localhost:8001"
  cloud:
    config:
      fail-fast: true
      username: user
      password: bankconfigadmin123