services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_EXTERNAL_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    networks:
      - bank-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  config-service:
    build:
      context: ./config-service
    container_name: config-service
    ports:
      - "${CONFIG_SERVICE_PORT:-8001}:8001"
    environment:
      SPRING_PROFILES_ACTIVE: native
      SPRING_SECURITY_USER_NAME: ${SPRING_SECURITY_USER}
      SPRING_SECURITY_USER_PASSWORD: ${SPRING_SECURITY_PASSWORD}
    volumes:
      - ./config-service/src/main/resources/services:/app/config
    healthcheck:
      test: ["CMD-SHELL", "curl -f -u $SPRING_SECURITY_USER:$SPRING_SECURITY_PASSWORD http://localhost:8001/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - bank-net

  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    container_name: discovery-service
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - "${DISCOVERY_SERVICE_PORT:-8761}:8761"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://${SPRING_SECURITY_USER}:${SPRING_SECURITY_PASSWORD}@config-service:8001
      SPRING_CLOUD_CONFIG_FAIL_FAST: "true"
    networks:
      - bank-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  bill-service:
    build:
      context: .
      dockerfile: bill-service/Dockerfile
    container_name: bill-service
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - "${BILL_SERVICE_PORT}:8082"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka
      SPRING_CONFIG_IMPORT: configserver:http://${SPRING_SECURITY_USER}:${SPRING_SECURITY_PASSWORD}@config-service:8001
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bill_service_database
      SPRING_DATASOURCE_USERNAME: ${BILL_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${BILL_DB_PASSWORD}
      DEPOSIT_MIN_AMOUNT: ${DEPOSIT_MIN_AMOUNT}
    networks:
      - bank-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  account-service:
    build:
      context: .
      dockerfile: account-service/Dockerfile
    container_name: account-service
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      postgres:
        condition: service_healthy
      bill-service:
        condition: service_healthy
    ports:
      - "${ACCOUNT_SERVICE_PORT}:8081"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka
      SPRING_CONFIG_IMPORT: configserver:http://${SPRING_SECURITY_USER}:${SPRING_SECURITY_PASSWORD}@config-service:8001
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/account_service_database
      SPRING_DATASOURCE_USERNAME: ${ACCOUNT_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${ACCOUNT_DB_PASSWORD}
    networks:
      - bank-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  deposit-service:
    build:
      context: .
      dockerfile: deposit-service/Dockerfile
    container_name: deposit-service
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      postgres:
        condition: service_healthy
      bill-service:
        condition: service_healthy
      account-service:
        condition: service_healthy
    ports:
      - "${DEPOSIT_SERVICE_PORT}:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka
      SPRING_CONFIG_IMPORT: configserver:http://${SPRING_SECURITY_USER}:${SPRING_SECURITY_PASSWORD}@config-service:8001
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/deposit_service_database
      SPRING_DATASOURCE_USERNAME: ${DEPOSIT_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DEPOSIT_DB_PASSWORD}
    networks:
      - bank-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    container_name: notification-service
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka
      SPRING_CONFIG_IMPORT: configserver:http://${SPRING_SECURITY_USER}:${SPRING_SECURITY_PASSWORD}@config-service:8001
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    networks:
      - bank-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  gateway-service:
    build:
      context: .
      dockerfile: gateway-service/Dockerfile
    container_name: gateway-service
    depends_on:
      discovery-service:
        condition: service_healthy
      account-service:
        condition: service_healthy
      bill-service:
        condition: service_healthy
      deposit-service:
        condition: service_healthy
      notification-service:
        condition: service_healthy
    ports:
      - "${GATEWAY_SERVICE_PORT}:8989"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka
      SPRING_CONFIG_IMPORT: configserver:http://${SPRING_SECURITY_USER}:${SPRING_SECURITY_PASSWORD}@config-service:8001
    networks:
      - bank-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989/actuator/health" ]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 10s

networks:
  bank-net:
    driver: bridge

volumes:
  postgres_data: