spring:
  application:
    name: gateway-service
  config:
    import: "configserver:http://${SPRING_SECURITY_USER_NAME}:${SPRING_SECURITY_PASSWORD}@config-service:8001"
  cloud:
    config:
      fail-fast: true