spring:
  application:
    name: bill-service
  config:
    import: "configserver:http://config-service:8001"
  cloud:
    config:
      fail-fast: true
      username: ${SPRING_SECURITY_USER}
      password: ${SPRING_SECURITY_PASSWORD}