spring:
  application:
    name: discovery-service
  config:
    import: "configserver:http://${SPRING_SECURITY_USER_NAME}:${SPRING_SECURITY_PASSWORD}@config-service:8001"
  cloud:
    config:
      fail-fast: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
    peer-node-read-timeout-ms: 100000