server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/account_service_database
    username: ${ACCOUNT_DB_USER}
    password: ${ACCOUNT_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml