spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bill_service_database
    username: bill_service_admin
    password: billserviceadmin
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  port: 8082