server:
  port: 9999

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://postgres:5432/notification_service_database
    username: ${NOTIFICATION_DB_USER:notification_service_admin}
    password: ${NOTIFICATION_DB_PASSWORD:notificationserviceadmin}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  health:
    mail:
      enabled: false
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
