#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<EOSQL
CREATE USER ${KEYCLOAK_DB_USER} WITH PASSWORD '${KEYCLOAK_DB_PASSWORD}';
CREATE DATABASE keycloak_database OWNER ${KEYCLOAK_DB_USER};
GRANT ALL PRIVILEGES ON DATABASE keycloak_database TO ${KEYCLOAK_DB_USER};
EOSQL