spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:/app/config
      enabled: false
  profiles:
    active: native
  security:
    user:
      password: bankconfigadmin123

server:
  port: 8001

management:
   endpoints:
     web:
       exposure:
         include: health,info
   endpoint:
     health:
       show-details: always