spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/services/, file:./config/
      enabled: false
  profiles:
    active: native
  security:
    user:
      password: bankconfigadmin123

management:
   endpoints:
     web:
       exposure:
         include: health,info
   endpoint:
     health:
       show-details: always

server:
  port: 8001