spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/services/, file:./config/
  profiles:
    active: native
  security:
    user:
      name: ${SPRING_SECURITY_USER}
      password: ${SPRING_SECURITY_PASSWORD}

management:
   endpoints:
     web:
       exposure:
         include: health,info
   endpoint:
     health:
       show-details: always

server:
  port: 8001